import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div className="container">
            <h1>doresenhas</h1>
            <p>um cantinho para guardar as resenhas que fiz das minhas leituras mais recentes</p>
            <div className="buttons">
            <button type="submit" className="buttonHeader">
                  <a href="https://www.instagram.com/dolivros/">instagram</a>
            </button>
            <button type="submit" className="buttonHeader">
                  <a href="https://www.goodreads.com/user/show/140364258-dora">goodreads</a>
            </button>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
